create database bd2;
use bd2;
ALTER TABLE piloto add (pil_fone varchar(15), pil_dt_nasc date, pil_cidade varchar(30));
ALTER TABLE piloto modify pil_nome varchar(30);
ALTER TABLE piloto modify pil_endereco varchar(70);
ALTER TABLE piloto RENAME COLUMN pil_codigo to pil_cod;
ALTER TABLE descendente ADD (desc_endereco varchar(70), desc_CPF varchar(11), desc_cidade varchar(30));
ALTER TABLE descendente modify desc_nome varchar(30);
ALTER TABLE descendente RENAME COLUMN desc_codigo to desc_cod;
ALTER TABLE aviao drop av_matricula;
ALTER TABLE aviao add “av_ano_fabric integer;
ALTER TABLE aviao RENAME COLUMN av_codigo to av_cod;
ALTER TABLE cidade modify cid_nome varchar(25);
ALTER TABLE cidade RENAME COLUMN cid_codigo to cid_cod;
ALTER TABLE voo RENAME COLUMN pil_codigo to pil_cod;
ALTER TABLE voo RENAME COLUMN av_codigo to av_cod;
ALTER TABLE voo RENAME COLUMN voo_codigo to voo_cod;
ALTER TABLE descendente RENAME TO tb_descendente;
ALTER TABLE piloto RENAME TO tb_piloto;
ALTER TABLE aviao RENAME TO tb_aviao;
ALTER TABLE voo RENAME TO tb_voo;
ALTER TABLE cidade RENAME TO tb_cidade;
ALTER TABLE possui RENAME TO tb_parentesco;
